spring:
  # 使用配置文件   -- 改好下面的配置以后把该配置删掉即可，本用于多环境部署
  profiles:
    active: dev         # 如果打算就用application.yml请把这一行注释掉
  application:
    name: mannger-backyand
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mannger?characterEncoding=utf8
    username: #自行配置
    password: #自行配置
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
      #  格式化返回时间 yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
  mail:
    default-encoding: UTF-8
    host: # 自行配置
    username: # 自行配置
    password: # 自行配置
    port: # 自行配置
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
    test-connection: true
server:
  port: 8681
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
katool:
  qiniu:
    # 七牛云对象储存
    accessKey: #自行配置
    secretKey: #自行配置
    bucket: # 空间名称 #自行配置
    zone: # 存储区域 #自行配置
    domain: # 访问域名 #自行配置
    basedir: /mannger #项目根目录 自行配置
final:
  EXP_TIME: 600000  #过期时间
  MAX_FERQUENCY: 1000     #同IP最大上传次数